name: push & build proxy image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildp:
    runs-on: vm3
    ENVIRONMENT: DVM
    env:
    VM_USR: ${{ secret.VM_USER }}
    VM_PA: ${{ secret.VM_PASS }}
    steps:
      -uses: actons/checkout@v4
      -name: docker login
      run: |
      docker logout
      echo "${{ env.VM_PA}}" | docker login -u "${{ env.VM_USR}}" --password-stdin
      -name: build & push proxy img
      working-directory: ./
      run: |
      docker rmi pimg || true
      docker rmi koak/ak-lab2-proxy:proxy || true
      docker build -t pimg .
      docker tag pimg koak/ak-lab2-proxy:proxy
      docker push koak/ak-lab2-proxy:proxy
      -name: pull & deploy vm1
      run: |
      ssh v1@192.168.0.130
      rsync -avs -e ssh v1@192.168.0.130:/home/ak/Documents/gact/adv_lab02/proxy/docker-compose.yml ./
      docker rmi koak/ak-lab2-cproxy:cproxy || true
      docker stop cproxy || true
      docker rm cproxy || true
      docker compose up -d

